project_id          = "gcp-course-2024"
zone              = "southamerica-west1-a"
region             = "southamerica-west1"
environment         = "prod"
path_to_credentials = "../../../../../../keys/service-account.json"